#!/bin/bash

# imgur script by Phil Tang <tangphillip@gmail.com>
# Based the work of Bart Nagel <bart@tremby.net>
# Shared with a Creative Commons Attribution 3.0 Unported License.

# API Key provided by Alan@imgur.com
# If you have rate limit issues, get your own at http://api.imgur.com/
apikey="b3625162d3418ac51a9ee805b1840452"

# function to output usage instructions
function usage {
	echo "Usage: $(basename $0) <filename>
Upload an image to imgur and output its new URL to stdout. Its delete page is
output to stderr.
If xsel or xclip is available, the URL is put on the X selection for easy
pasting." >&2
}

# check API key has been entered
if [ "$apikey" = "Your API key" ]; then
	echo "You first need to edit the script and put your API key in the variable near the top." >&2
	exit 15
fi

# check arguments
if [ "$1" = "-h" -o "$1" = "--help" ]; then
	usage
	exit 0
elif [ $# -ne 1 ]; then
	if [ $# == 0 ]; then
		echo "No file specified" >&2
	else
		echo "Unexpected arguments" >&2
	fi
	usage
	exit 16
elif [ ! -f "$1" ]; then
	echo "File \"$1\" not found" >&2
	exit 1
fi

# check curl is available
which curl >/dev/null 2>/dev/null || {
	echo "Couln't find curl, which is required." >&2
	exit 17
}

# upload the image
response=$(curl -F "key=$apikey" -H "Expect: " -F "image=@$1" \
	http://imgur.com/api/upload.xml 2>/dev/null)
# the "Expect: " header is to get around a problem when using this through the
# Squid proxy. Not sure if it's a Squid bug or what.
if [ $? -ne 0 ]; then
	echo "Upload failed" >&2
	exit 2
elif [ $(echo $response | grep -c "<error_msg>") -gt 0 ]; then
	echo "Error message from imgur:" >&2
	echo $response | sed -E 's/.*<error_msg>(.*)<\/error_msg>.*/\1/' >&2
	exit 3
fi

# parse the response and output our stuff
url=$(echo $response | sed -E 's/.*<original_image>(.*)<\/original_image>.*/\1/')
deleteurl=$(echo $response | sed -E 's/.*<delete_page>(.*)<\/delete_page>.*/\1/')
echo $url
echo "Delete page: $deleteurl" >&2

# put the URL on the clipboard if we have xsel or xclip
if [ $DISPLAY ]; then
	{ which pbcopy >/dev/null 2>/dev/null && echo -n $url | pbcopy; } \
        || { which xsel >/dev/null 2>/dev/null && echo -n $url | xsel; } \
            || { which xclip >/dev/null 2>/dev/null && echo -n $url | xclip; } \
            || echo "Haven't copied to the clipboard: no pbcopy, xsel, or xclip" >&2
else
	echo "Haven't copied to the clipboard: no \$DISPLAY" >&2
fi
